name: Build a Windows executable

on:
  workflow_run:
    workflows: ["Build & Lint & Deploy"]
    branches: [main]
    types:
      - completed

jobs:
  pyinstaller_win:
    runs-on: windows-latest
    if: ${{ !github.event.issue.pull_request }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          pip install pyinstaller

      - name: Build a Windows executable
        run: |
         python win_build.py

      - name: Determine next build number
        uses: MCKanpolat/auto-semver-action@1.0.5
        id: versioning
        with:
          releaseType: patch
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a release archive
        run: |
          powershell Compress-Archive dist/* BasementRenovator.zip

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "BasementRenovator.zip"
          tag: ${{steps.versioning.outputs.version}}
          token: ${{ secrets.GITHUB_TOKEN }}
